# -*- coding: utf-8 -*-
"""ANALISE DE REGRESSÃO LINEAR - EVOLUÇÃO DO QUANTITATIVO ELEITORAL, NÚMEROS DO COMPARECIMENTO/ABSTENÇÃO – MUNICÍPIO DE JUCATI - PE - 2014/2020 - IA - UNIVERSIDADE DE PERNAMBUCO - UPE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Am3UeCxLy4Xx4O-FoK6uJg1F95QwHcgs
"""

# Importe o numpy 
import numpy as np

# variavel X contendo o numero de elitores aptos a votar em todos os trunos das eleiçoes de 2014 a 2020 respectivamente, municipio de Jucati-PE
x = np.array([9.299, 9.299, 8.670, 8.803, 8.803]).reshape((-1,1))

# Variavel Y contendo o numero de votos validos em todos os trunos das eleiçoes de 2014 a 2020 respectivamente, municipio de Jucati-PE
y = np.array([6.748, 6.684, 8.089, 7.046, 7.251])

# Import biblioteca de regressão linear sklearn
from sklearn.linear_model import LinearRegression

# Criação do modelo de regressão linear, fazendo o fit de x e y.
modelo = LinearRegression().fit(x,y)

# Testando o modelo  para aferição do seu score, interceção e inclinassão
modelo.score(x,y)
modelo.intercept_
modelo.coef_

# Variavel vota contendo o numero de eleitores aptos a votar em 2020 no municipio de Jucati-PE
vota = np.array([9.587]).reshape((-1,1))

# Apliquecação o modelo criado fazendo uma previsão do numero de votos validos nas eleições de 2020 no municipio de Jucati-PE
previsao = modelo.predict(vota)

# Imprimindo dados usados no dataset, e o resultado da previsao, com calculo de votos validos e nulos de acordo com o total do ano de 2020
print('|  Ano |   Turno  | Eleitores aptos | Comparecimento | Abstenção |')
print('| 2014 | 1º Turno |      9.299      |      6.748     |   2.551   |')
print('| 2014 | 2º Turno |      9.299      |      6.684     |   2.615   |')
print('| 2016 | 1º Turno |      8.670      |      8.089     |    581    |')
print('| 2018 | 1º Turno |      8.803      |      7.046     |   1.757   |')
print('| 2018 | 2º Turno |      8.803      |      7.251     |   1.552   |')
print('| 2020 | 1º Turno |      9.587      |     ', ("%.3f" % numero2),'    |  ',("%.3f" % numero1), '  |')
print('')

calc= 9.587-previsao
numero1 = calc
numero2 = previsao

print('Provavel numero de Votos Validos nas eleiçoes de 2020, no municipio de Jucati-PE:', ("%.3f" % numero2))